default: &default
  adapter: mysql2
  encoding: utf8
  username: 11_szmigiel
  password: epi123
  host: localhost
  port: 3306

development:
  <<: *default
  database: webbooks_development

test:
  <<: *default
  database: webbooks_test

production:
  <<: *default
  database: 11_szmigiel
